name: dispatch target file updated

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  dispatch-target-updated:
    name: dispatch-target-updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Dispatch target-updated
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.COMMON_REPO_ACCESS_TOKEN }}
          repository: tsubasa-admin/test_repo
          event-type: target-updated

      - name: Dispatch target-updated for another repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.COMMON_REPO_ACCESS_TOKEN }}
          repository: tsubasa-admin/test_wr_repo
          event-type: target-updated